spring:
  profiles:
    #active: local, redis
    active: local, local cache

---
# DATABASE
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/sbb
    driver-class-name: org.postgresql.Driver
    username: web
    password: web
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      #       ddl-auto: create
      ddl-auto: update

# logging
logging:
  level:
    root: INFO
    org:
      springframework: INFO
    io:
      dustin:
        apps: INFO

server:
  error:
    whitelabel:
      enabled: false
  port: 8881

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /dustin
    defaultModelsExpandDepth: -1
    tagsSorter: alpha

feign:
  client:
    config:
      test:
        connectTimeout: 10000 # 10?
        readTimeout: 10000 # 10?
        url: http://localhost:8881/api/v1/feign

# 실무에서는 private 하게 관리하자
jwt:
  issuer: basquiat
  subject: musicshop
  # 초단위 3600 -> 1시간
  expired-at: 30
  #expired-at: 60
  # Jean-Michel Basquiat가 사망한 날짜
  secret: dustin19880812
  prefix: Bearer

cached:
  # 초로 받는다.
  expired-at: 20
